---
font: JetBrainsMono Nerd Font 14
background: "#EFF1F5d0"
color: "#4C4F69"
border: "#7287FD"
separator: " âžœ "
border_width: 3
corner_r: 2
padding: 15
rows_per_column: 6
column_padding: 25

# One of center, left, right, top, bottom, bottom-left, top-left, etc.
anchor: bottom
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 30
margin_left: 0
margin_top: 0

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

menu:
  - key: ["Ctrl+Left", "Ctrl+h"]
    keep_open: true
    desc: Move the focused workspace to the monitor to the left
    cmd: niri msg action move-workspace-to-monitor-left
  - key: ["Ctrl+Right", "Ctrl+l"]
    keep_open: true
    desc: Move the focused workspace to the monitor to the right
    cmd: niri msg action move-workspace-to-monitor-right
  - key: ["Ctrl+Down", "Ctrl+j"]
    keep_open: true
    desc: Move the focused workspace to the monitor below
    cmd: niri msg action move-workspace-to-monitor-down
  - key: ["Ctrl+Up", "Ctrl+k"]
    keep_open: true
    desc: Move the focused workspace to the monitor above
    cmd: niri msg action move-workspace-to-monitor-up

  - key: [Down, j]
    keep_open: true
    desc: Move the focused workspace down
    cmd: niri msg action move-workspace-down
  - key: [Up, k]
    keep_open: true
    desc: Move the focused workspace up
    cmd: niri msg action move-workspace-up

  - key: ["1"]
    keep_open: true
    desc: Move the focused workspace to index 1
    cmd: niri msg action move-workspace-to-index 1
  - key: ["2"]
    keep_open: true
    desc: Move the focused workspace to index 2
    cmd: niri msg action move-workspace-to-index 2
  - key: ["3"]
    keep_open: true
    desc: Move the focused workspace to index 3
    cmd: niri msg action move-workspace-to-index 3
  - key: ["4"]
    keep_open: true
    desc: Move the focused workspace to index 4
    cmd: niri msg action move-workspace-to-index 4
  - key: ["5"]
    keep_open: true
    desc: Move the focused workspace to index 5
    cmd: niri msg action move-workspace-to-index 5
  - key: ["6"]
    keep_open: true
    desc: Move the focused workspace to index 6
    cmd: niri msg action move-workspace-to-index 6
  - key: ["7"]
    keep_open: true
    desc: Move the focused workspace to index 7
    cmd: niri msg action move-workspace-to-index 7
  - key: ["8"]
    keep_open: true
    desc: Move the focused workspace to index 8
    cmd: niri msg action move-workspace-to-index 8
  - key: ["9"]
    keep_open: true
    desc: Move the focused workspace to index 9
    cmd: niri msg action move-workspace-to-index 9

  - key: ["m"]
    desc: Use move mode
    cmd: {{ wlr-which-key }} move
  - key: ["f"]
    desc: Use focus mode
    cmd: {{ wlr-which-key }} focus
  - key: ["r"]
    desc: Use resize mode
    cmd: {{ wlr-which-key }} resize
